db_query("names",{name:'tom'},function(d){
	var list='';
	for(i=0;i<d.length;i++){
		list+='<li>';
		list+=d[i].name;
		list+='</li>';
	}
	console.log(1<d.length);
	data=data.setValue({
		'{title}':d[0].name,
		'{time}':'2015-01-25',
		'{site}':'codetyphon',
		'{list}':list
	});
	render();
},function(err){
	data=err;
	render();
});
